### ISSUE TITLE
Why is Try delegate returning Exceptional?

### ISSUE THREAD

**Issue by slimshader** [la-yumba/functional-csharp-code-2#13]
Hi, I don’t get why Try delegate is returning Exceptional if it is Run()ks purpose to wrap the result of the lambda call. Invoking „raw” Try delegate can still throw exception but return type of Exceptinal suggests that ir will not happen or am I completly off here?

**Comment by la-yumba** [comment]
You're not completely off... ideally, one would like to "override" function invocation (what you call "raw" invocation). Since this is not possible, I defined Run(). "Raw" invocation of course completely defeats the purpose of Try, but again there's no way to prevent it.

**Comment by slimshader** [comment]
so what do you think about making Try a struct wrapper around a Func<> disabling possibility to bypass Run()?

**Comment by la-yumba** [comment]
Yes, that would be possible, but it would introduce syntactic noise because you'd always have to instantiate the struct. For example, instead of 
```
 Try<Uri> CreateUri(string uri) => () => new Uri(uri);
```
you'd have to write
```
 Try<Uri> CreateUri(string uri) => new Try(() => new Uri(uri));
```
This is because you cannot implicitly convert a lambda to a struct. (You could simplify this a bit by just writing `new` or just `Try`, assuming that's a statically imported method, but you're still adding one level of parentheses.) Try rewriting something a bit complex, like `SelectMany` for this struct implementation of `Try`, and you'll see that it does hurt readability.
