### ISSUE TITLE
Will the 2nd edition reference Language-Ext?

### ISSUE THREAD

**Issue by MrYossu** [la-yumba/functional-csharp-code-2#7]
Just discovered that you're writing a 2nd edition! Excellent news, my copy is getting very dog-eared from having been read many times!

Anyway, without wishing to be rude, may I make a request (that may be too late). The only drawback I felt the book had was that you used your own library, instead of using Language-Ext. I understand the educational reasons for developing a library as you went along, but at the end of the day, you yourself recommend Language-Ext as "_a more fully-fledged functional library_."

Thing is, Language-Ext suffers badly from a lack of good documentation. Your book could easily be that documentation, making it even more useful than it already is. Even if you just added a small paragraph at the end of each section showing how the concepts and code you just described would be done in Language-Ext, it would give a kick-start to those of us who are keen to put your ideas into practice, but are struggling to translate them.

This is **NOT** meant in any way to put down La Yumba, it's meant as a constructive comment to give the book a whole new dimension.

Thanks for listening, and thanks for writing what is (in my opinion anyway) probably the most important C# book ever written. Really, I mean that, no flattery here!

**Comment by la-yumba** [comment]
Hi @MrYossu, 
thanks for your enthusiasm and your suggestion. 
Indeed, it is a bit late, as the 2nd edition is in the production phase and should be available soon (the MEAP is already available, of course). 
I do understand your suggestion. The thing is, the "release cycle" of a book and an open source library are so different, that they would be inevitably become out of sync. For example, I was able to make all the code for the 2nd edition target .NET 6 and C# 10. So at this moment my book is "ahead" of language-ext, and I can illustrate functional features in the latest C# language and .NET libraries. But in, say, 3 years, my book will likely have fallen behind language-ext. 
In the future, language-ext may introduce breaking changes, new ways of doing things, or be superseded by another, similar library (say, one developed by the .NET foundation, you never know). That would "break" the code in the book, or render it obsolete, and that would be a nuisance to anyone reading the book then. That's why I choose to decouple the book from language-ext.

**Comment by hannah23280** [comment]
> Thing is, Language-Ext suffers badly from a lack of good documentation. Your book could easily be that documentation, making it even more useful than it already is. Even if you just added a small paragraph at the end of each section showing how the concepts and code you just described would be done in Language-Ext, it would give a kick-start to those of us who are keen to put your ideas into practice, but are struggling to translate them.

I second to this suggestion. 
Although I understood the "release cycle" of a book and an open source library are different, that they would be inevitably become out of sync, but that is of something unavoidable (sadly). Cos if every technical author is to start implementing their own feature, instead of using the one that comes with library, those readers who want to quick start using the library would not be able do so easily (at least not without some effort).

Imagine the scenario where an angular book's author worries angular framework will eventually go out of sync (angular updates every 6 month) with his book, so he decides to illustrate how he implements his own framework to closely match the angular framework.

That's say, i have to admit this book is really a very good book. I manage to read further into this book. and understand stuff better than any other functional programming books. Thanks for producing such a good book.
